apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: demo-cluster
  namespace: demo-ns
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: guaranteed-medium
      storageClass: vc01cl01-t0compute
      tkr:  
        reference:
          name: v1.22.9---vmware.1-tkg.1.cc71bc8
    nodePools:
    - name: worker-nodepool-demo-cluster
      replicas: 3
      vmClass: guaranteed-xlarge
      storageClass: vc01cl01-t0compute
      tkr:  
        reference:
          name: v1.22.9---vmware.1-tkg.1.cc71bc8
