apiVersion: v1
kind: Service
metadata:
  name: echoserver
  labels:
    app: echoserver
spec:
  type: LoadBalancer
  loadBalancerIP: 10.220.65.11
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: echoserver
